// Generated by scripts/build-standalone-release.mjs. Do not edit.
export const RELEASE_VERSION = "ee9df89";

export type MigrationSentinel = { kind: "table"; name: string } | { kind: "column"; name: string; column: string };
export type Migration = { name: string; statements: string[]; sentinel: MigrationSentinel | null };

export const MIGRATIONS: Migration[] = [
  {
    "name": "0001_init.sql",
    "statements": [
      "CREATE TABLE IF NOT EXISTS meetings (\n  id TEXT PRIMARY KEY,\n  title TEXT NOT NULL,\n  template TEXT NOT NULL DEFAULT 'workshop',\n  language TEXT NOT NULL DEFAULT 'auto',\n  status TEXT NOT NULL DEFAULT 'recording',\n  started_at TEXT NOT NULL,\n  ended_at TEXT,\n  expected_chunks INTEGER,\n  processed_chunks INTEGER NOT NULL DEFAULT 0,\n  summary_status TEXT NOT NULL DEFAULT 'waiting',\n  summary_json TEXT,\n  summary_markdown TEXT,\n  summary_enqueued_at TEXT,\n  last_error TEXT,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE TABLE IF NOT EXISTS audio_chunks (\n  id TEXT PRIMARY KEY,\n  meeting_id TEXT NOT NULL,\n  sequence INTEGER NOT NULL,\n  r2_key TEXT NOT NULL,\n  mime_type TEXT NOT NULL,\n  duration_ms INTEGER NOT NULL DEFAULT 0,\n  size_bytes INTEGER NOT NULL DEFAULT 0,\n  status TEXT NOT NULL DEFAULT 'uploaded',\n  transcript_text TEXT,\n  transcript_json TEXT,\n  retry_count INTEGER NOT NULL DEFAULT 0,\n  last_error TEXT,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,\n  UNIQUE (meeting_id, sequence)\n)",
      "CREATE INDEX IF NOT EXISTS idx_chunks_meeting_sequence\n  ON audio_chunks(meeting_id, sequence)",
      "CREATE INDEX IF NOT EXISTS idx_chunks_status\n  ON audio_chunks(status)",
      "CREATE TABLE IF NOT EXISTS job_events (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  meeting_id TEXT NOT NULL,\n  chunk_id TEXT,\n  event_type TEXT NOT NULL,\n  detail TEXT,\n  created_at TEXT NOT NULL\n)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "meetings"
    }
  },
  {
    "name": "0002_segments.sql",
    "statements": [
      "-- Rolling 5-minute segment notes.\n--\n-- A segment is a contiguous run of transcribed chunks covering roughly five\n-- minutes. Segments are summarised while the meeting is still running, so the\n-- final note is a cheap merge of short segment notes instead of one giant\n-- pass over a two-hour transcript.\n\nCREATE TABLE IF NOT EXISTS meeting_segments (\n  id TEXT PRIMARY KEY,\n  meeting_id TEXT NOT NULL,\n  seq INTEGER NOT NULL,\n  start_chunk INTEGER NOT NULL,\n  end_chunk INTEGER NOT NULL,\n  duration_ms INTEGER NOT NULL DEFAULT 0,\n  status TEXT NOT NULL DEFAULT 'queued',\n  notes_json TEXT,\n  headline TEXT,\n  retry_count INTEGER NOT NULL DEFAULT 0,\n  last_error TEXT,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,\n  UNIQUE (meeting_id, seq)\n)",
      "CREATE INDEX IF NOT EXISTS idx_segments_meeting_seq\n  ON meeting_segments(meeting_id, seq)",
      "CREATE INDEX IF NOT EXISTS idx_segments_status\n  ON meeting_segments(status)",
      "-- Set by POST /api/meetings/:id/force-summary. Lets the final note be built\n-- from whatever transcribed successfully, instead of waiting forever for a\n-- chunk that will never finish.\nALTER TABLE meetings ADD COLUMN force_summary INTEGER NOT NULL DEFAULT 0"
    ],
    "sentinel": {
      "kind": "table",
      "name": "meeting_segments"
    }
  },
  {
    "name": "0003_ai_usage.sql",
    "statements": [
      "-- Workers AI consumption, measured rather than estimated.\n--\n-- Every Workers AI response carries usage.neurons, which is the unit Cloudflare\n-- bills and rate-limits in. Recording it per call is what makes the question\n-- \"how much longer can I record today?\" answerable, and it needs no API token\n-- and no call off the account.\n\nCREATE TABLE IF NOT EXISTS ai_usage (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  meeting_id TEXT,\n  kind TEXT NOT NULL,               -- asr | segment | final\n  model TEXT NOT NULL,\n  neurons REAL NOT NULL DEFAULT 0,\n  audio_ms INTEGER NOT NULL DEFAULT 0,\n  raw_usage TEXT,\n  day TEXT NOT NULL,                -- UTC date; Cloudflare's free allocation resets at 00:00 UTC\n  created_at TEXT NOT NULL\n)",
      "CREATE INDEX IF NOT EXISTS idx_usage_day ON ai_usage(day)",
      "CREATE INDEX IF NOT EXISTS idx_usage_meeting ON ai_usage(meeting_id)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "ai_usage"
    }
  },
  {
    "name": "0004_owner_passkeys.sql",
    "statements": [
      "-- Meeting Note has one user: whoever deployed it. They sign in with a passkey.\n-- Times here are epoch milliseconds.\n\nCREATE TABLE owners (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  -- The random handle this owner is known by inside each passkey.\n  webauthn_user_id TEXT NOT NULL UNIQUE,\n  created_at INTEGER NOT NULL,\n  -- At most one owner, enforced by the database: two people racing to claim a fresh\n  -- deployment cannot both win.\n  singleton INTEGER NOT NULL DEFAULT 1 UNIQUE CHECK (singleton = 1)\n)",
      "CREATE TABLE credentials (\n  id TEXT PRIMARY KEY,                -- base64url credential id, as the browser reports it\n  owner_id TEXT NOT NULL REFERENCES owners (id) ON DELETE CASCADE,\n  public_key TEXT NOT NULL,           -- base64url COSE public key\n  counter INTEGER NOT NULL DEFAULT 0,\n  transports TEXT NOT NULL DEFAULT '[]',\n  created_at INTEGER NOT NULL,\n  last_used_at INTEGER\n)",
      "-- Only the SHA-256 of a session token is stored; the token itself lives in the owner's cookie.\nCREATE TABLE sessions (\n  token_hash TEXT PRIMARY KEY,\n  owner_id TEXT NOT NULL REFERENCES owners (id) ON DELETE CASCADE,\n  expires_at INTEGER NOT NULL,\n  created_at INTEGER NOT NULL\n)",
      "-- One-time WebAuthn challenges, kept for five minutes.\nCREATE TABLE challenges (\n  id TEXT PRIMARY KEY,\n  purpose TEXT NOT NULL CHECK (purpose IN ('register', 'login')),\n  challenge TEXT NOT NULL,\n  payload TEXT NOT NULL DEFAULT '{}',\n  expires_at INTEGER NOT NULL\n)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "owners"
    }
  },
  {
    "name": "0005_owner_recovery_code.sql",
    "statements": [
      "-- A recovery code, shown once when the owner sets the app up, replaces the setup code a\n-- deploy form would otherwise have to ask for. Only its SHA-256 is stored; it is replaced\n-- every time it is used.\nALTER TABLE owners ADD COLUMN recovery_hash TEXT"
    ],
    "sentinel": {
      "kind": "column",
      "name": "owners",
      "column": "recovery_hash"
    }
  },
  {
    "name": "0006_plans_and_tasks.sql",
    "statements": [
      "-- Plans on their way to a calendar: what the owner says aloud (\"next Tuesday at 3, call\n-- Cindy\"), and later the to-dos pulled out of meetings.\n--\n-- Everything the AI finds starts as 'suggested' and only reaches a calendar once the owner\n-- confirms it. Cancelled plans are kept, so a subscribed calendar learns to remove them.\n\nCREATE TABLE IF NOT EXISTS settings (\n  key TEXT PRIMARY KEY,\n  value TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "-- The words only. The recording itself is transcribed straight away and never stored.\nCREATE TABLE IF NOT EXISTS dictations (\n  id TEXT PRIMARY KEY,\n  transcript TEXT NOT NULL,\n  duration_ms INTEGER NOT NULL DEFAULT 0,\n  timezone TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'done',        -- done | not_understood\n  last_error TEXT,\n  created_at TEXT NOT NULL                     -- relative dates were resolved against this\n)",
      "CREATE TABLE IF NOT EXISTS tasks (\n  id TEXT PRIMARY KEY,\n  title TEXT NOT NULL,\n  notes TEXT NOT NULL DEFAULT '',\n  kind TEXT NOT NULL DEFAULT 'task',           -- task: get something done | event: happens at a time\n  status TEXT NOT NULL DEFAULT 'suggested',    -- suggested | confirmed | done | cancelled\n  all_day INTEGER NOT NULL DEFAULT 1,\n  due_date TEXT,                               -- YYYY-MM-DD in `timezone`; NULL while it has no date\n  starts_at TEXT,                              -- UTC ISO, only when all_day = 0\n  ends_at TEXT,\n  timezone TEXT NOT NULL,\n  repeat_hint TEXT NOT NULL DEFAULT '',        -- \"every Monday\", as said; not expanded into dates\n  assignee TEXT NOT NULL DEFAULT '',           -- who a meeting's to-do belongs to\n  source TEXT NOT NULL,                        -- dictation | meeting | manual\n  dictation_id TEXT,\n  meeting_id TEXT,\n  segment_seq INTEGER,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE INDEX IF NOT EXISTS idx_tasks_status_due ON tasks(status, due_date)",
      "CREATE INDEX IF NOT EXISTS idx_tasks_dictation ON tasks(dictation_id)",
      "CREATE INDEX IF NOT EXISTS idx_tasks_meeting ON tasks(meeting_id)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "settings"
    }
  },
  {
    "name": "0007_memory.sql",
    "statements": [
      "-- Memory: everything the owner may want to find again, as short passages. Transcript pieces,\n-- section notes, final notes, plans and dictations are copied in as they're written, and a\n-- full-text index keeps them searchable by any word, in English or Chinese.\n--\n-- The trigram tokenizer matches any run of three or more characters, which works for Chinese\n-- without a word segmenter; shorter Chinese words fall back to LIKE. Keep writes to\n-- memory_items as INSERT … ON CONFLICT DO UPDATE: INSERT OR REPLACE deletes rows without\n-- firing the delete trigger, which would leave the index out of step.\n\nCREATE TABLE IF NOT EXISTS memory_items (\n  id TEXT PRIMARY KEY,                -- transcript:<chunk>:<n> | section:<segment> | summary:<meeting> | plan:<task> | dictation:<id>\n  kind TEXT NOT NULL,                 -- transcript | section | summary | plan | dictation | fact\n  source_id TEXT NOT NULL,\n  meeting_id TEXT,\n  chunk_sequence INTEGER,             -- where to open the meeting's transcript\n  title TEXT NOT NULL DEFAULT '',\n  text TEXT NOT NULL,\n  occurred_at TEXT NOT NULL,          -- when it was said, or for a plan, when it happens (UTC ISO)\n  superseded_by TEXT,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE INDEX IF NOT EXISTS idx_memory_meeting ON memory_items(meeting_id)",
      "CREATE INDEX IF NOT EXISTS idx_memory_occurred ON memory_items(occurred_at)",
      "CREATE INDEX IF NOT EXISTS idx_memory_source ON memory_items(source_id)",
      "CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(\n  title,\n  text,\n  content = 'memory_items',\n  content_rowid = 'rowid',\n  tokenize = 'trigram'\n)",
      "CREATE TRIGGER IF NOT EXISTS memory_items_ai AFTER INSERT ON memory_items BEGIN\n  INSERT INTO memory_fts (rowid, title, text) VALUES (new.rowid, new.title, new.text);\nEND",
      "CREATE TRIGGER IF NOT EXISTS memory_items_ad AFTER DELETE ON memory_items BEGIN\n  INSERT INTO memory_fts (memory_fts, rowid, title, text) VALUES ('delete', old.rowid, old.title, old.text);\nEND",
      "CREATE TRIGGER IF NOT EXISTS memory_items_au AFTER UPDATE OF title, text ON memory_items BEGIN\n  INSERT INTO memory_fts (memory_fts, rowid, title, text) VALUES ('delete', old.rowid, old.title, old.text);\n  INSERT INTO memory_fts (rowid, title, text) VALUES (new.rowid, new.title, new.text);\nEND"
    ],
    "sentinel": {
      "kind": "table",
      "name": "memory_items"
    }
  },
  {
    "name": "0008_device_links.sql",
    "statements": [
      "-- Adding a phone or computer. A signed-in device makes a one-time link, shown as a QR code; the new\n-- device opens it and creates its own passkey, and every other device keeps working. Only the SHA-256\n-- of the link's token is stored, and a link works once, for ten minutes.\n--\n-- (Numbered 0008 so it sorts after migrations being developed elsewhere; wrangler applies any\n-- migration it hasn't seen, whatever its number.)\n\nCREATE TABLE IF NOT EXISTS device_links (\n  token_hash TEXT PRIMARY KEY,\n  owner_id TEXT NOT NULL REFERENCES owners (id) ON DELETE CASCADE,\n  expires_at INTEGER NOT NULL,\n  created_at INTEGER NOT NULL\n)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "device_links"
    }
  },
  {
    "name": "0009_memory_embeddings.sql",
    "statements": [
      "-- Semantic search over memory_items, on top of the full-text search from 0007. Embedding runs in\n-- its own queue job (see src/embed.ts), never in the request or job that wrote the memory, so\n-- these two columns say which rows still need it: embedded_at is when a row was last embedded,\n-- and embedded_hash is the SHA-256 of the text as of that embedding, so a later text change (a\n-- rewritten note, a superseded fact never reuses an id so this mostly covers edits-in-place) is\n-- noticed and queued again instead of silently going stale.\n--\n-- The vector itself lives in Vectorize (MEMORY_VECTORS), an optional binding: a copy without it\n-- never sets these columns and keeps searching full-text only, as it always has.\n\nALTER TABLE memory_items ADD COLUMN embedded_at TEXT",
      "ALTER TABLE memory_items ADD COLUMN embedded_hash TEXT",
      "-- Finds rows still owed an embedding; mostly NULL, which SQLite indexes just as well as any value.\nCREATE INDEX IF NOT EXISTS idx_memory_embedded_at ON memory_items(embedded_at)",
      "-- Speeds up GET /api/memory?kind=&cursor=, which orders by occurred_at within a kind.\nCREATE INDEX IF NOT EXISTS idx_memory_kind_occurred ON memory_items(kind, occurred_at)"
    ],
    "sentinel": {
      "kind": "column",
      "name": "memory_items",
      "column": "embedded_at"
    }
  },
  {
    "name": "0010_integration_tokens.sql",
    "statements": [
      "CREATE TABLE integration_tokens (\n  id TEXT PRIMARY KEY,\n  owner_id TEXT NOT NULL,\n  label TEXT NOT NULL,\n  token_hash TEXT NOT NULL UNIQUE,\n  created_at INTEGER NOT NULL,\n  last_used_at INTEGER,\n  revoked_at INTEGER,\n  FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE\n)",
      "CREATE INDEX integration_tokens_owner_idx\n  ON integration_tokens(owner_id, revoked_at, created_at DESC)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "integration_tokens"
    }
  },
  {
    "name": "0011_audio_archive.sql",
    "statements": [
      "-- Permanent audio, for a copy that binds the optional RECORDINGS R2 bucket (see src/audio.ts). The\n-- one-click template never binds it: there, audio lives only in KV and expires after\n-- AUDIO_RETENTION_DAYS, and these columns simply stay at their defaults.\n--\n-- keep_audio is the owner's choice per meeting: 1 keeps a permanent copy of every chunk in R2, 0 keeps\n-- only the temporary KV copy (for a session where people were promised deletion after 7 days).\n-- archived_at says a chunk's permanent copy exists; audio_deleted_at that the owner deleted the audio,\n-- after which the transcript and notes remain but the chunk can't be played or transcribed again.\n\nALTER TABLE meetings ADD COLUMN keep_audio INTEGER NOT NULL DEFAULT 1",
      "ALTER TABLE audio_chunks ADD COLUMN archived_at TEXT",
      "ALTER TABLE audio_chunks ADD COLUMN audio_deleted_at TEXT",
      "-- Finds chunks still owed a permanent copy.\nCREATE INDEX IF NOT EXISTS idx_chunks_archived_at ON audio_chunks(archived_at)"
    ],
    "sentinel": {
      "kind": "column",
      "name": "meetings",
      "column": "keep_audio"
    }
  },
  {
    "name": "0012_captures_and_images.sql",
    "statements": [
      "-- Quick notes: text and phone-compressed WebP images. The original camera file never reaches\n-- the Worker. D1 keeps searchable metadata; the private image bytes live in the existing AUDIO\n-- KV namespace under images/ (without the seven-day audio expiry).\n\nCREATE TABLE captures (\n  id TEXT PRIMARY KEY,\n  title TEXT NOT NULL,\n  body TEXT NOT NULL DEFAULT '',\n  category TEXT NOT NULL DEFAULT 'inbox',\n  occurred_at TEXT NOT NULL,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL\n)",
      "CREATE INDEX captures_occurred_idx ON captures(occurred_at DESC, id DESC)",
      "CREATE INDEX captures_category_idx ON captures(category, occurred_at DESC)",
      "CREATE TABLE capture_attachments (\n  id TEXT PRIMARY KEY,\n  capture_id TEXT NOT NULL,\n  image_key TEXT NOT NULL UNIQUE,\n  thumbnail_key TEXT NOT NULL UNIQUE,\n  width INTEGER NOT NULL,\n  height INTEGER NOT NULL,\n  bytes INTEGER NOT NULL DEFAULT 0,\n  thumbnail_bytes INTEGER NOT NULL DEFAULT 0,\n  status TEXT NOT NULL DEFAULT 'pending',       -- pending | ready | failed\n  caption TEXT NOT NULL DEFAULT '',\n  ocr_text TEXT NOT NULL DEFAULT '',\n  ai_status TEXT NOT NULL DEFAULT 'off',        -- off | queued | processing | done | failed\n  last_error TEXT,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  FOREIGN KEY (capture_id) REFERENCES captures(id) ON DELETE CASCADE\n)",
      "CREATE INDEX capture_attachments_capture_idx ON capture_attachments(capture_id, created_at)",
      "CREATE INDEX capture_attachments_ai_idx ON capture_attachments(ai_status, created_at)"
    ],
    "sentinel": {
      "kind": "table",
      "name": "captures"
    }
  },
  {
    "name": "0013_hd_transcripts.sql",
    "statements": [
      "-- High-definition re-transcription: one Deepgram pass per chunk, with speaker numbers, plus the\n-- meeting-wide speaker list the owner can name. The ordinary Whisper transcript is left untouched;\n-- this sits beside it, and only exists for meetings whose owner asked for it and paid for it.\nCREATE TABLE hd_runs (\n  meeting_id TEXT PRIMARY KEY,\n  status TEXT NOT NULL DEFAULT 'queued',\n  model TEXT NOT NULL,\n  chunks_total INTEGER NOT NULL DEFAULT 0,\n  chunks_done INTEGER NOT NULL DEFAULT 0,\n  -- [{ id, label, name, seconds }] once the run has reconciled its per-chunk speaker numbers.\n  speakers_json TEXT,\n  last_error TEXT,\n  created_at TEXT NOT NULL,\n  updated_at TEXT NOT NULL,\n  FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE\n)",
      "-- Each chunk's diarized utterances: [{ speaker, start, end, text }], speaker numbered per chunk.\nALTER TABLE audio_chunks ADD COLUMN hd_json TEXT"
    ],
    "sentinel": {
      "kind": "table",
      "name": "hd_runs"
    }
  }
];
